export const GENARELINFORMATION = "GENARELINFORMATION";
export const ADDRESS = "ADDRESS";
export const CONTACTDETAIL = "CONTACTDETAIL";
export const CONTACTDETAILSOWNER = "CONTACTDETAILSOWNER";
export const BANKDETAILS = "BANKDETAILS";
export const LOGO = "LOGO";
export const INCREASECONTACTDETAILS = "INCREASECONTACTDETAILS";