export const GENARELINFORMATION = "GENARELINFORMATION";
export const ADDRESS = "ADDRESS";
export const SETLATLNG = "SETLATLNG";
export const CONTACTDETAIL = "CONTACTDETAIL";
export const ADDCONTACTDETAIL = "ADDCONTACTDETAIL";
export const ADDCONTACTDETAILDATA = "ADDCONTACTDETAILDATA";
export const CONTACTDETAILSOWNER = "CONTACTDETAILSOWNER";
export const BANKDETAILS = "BANKDETAILS";
export const LOGO = "LOGO";
export const INCREASECONTACTDETAILS = "INCREASECONTACTDETAILS";

//
export const SETINITIALDATA = "SETINITIALDATA";
export const BASICDETAILS = "BASICDETAILS";
export const ADDIMAGES = "ADDIMAGES";
export const REMOVEIMAGES = "REMOVEIMAGES";
export const ADDVIDEOS = "ADDVIDEOS";
export const REMOVEVIDEOS = "REMOVEVIDEOS";
export const ADDTYPECATEGORYCOLLECTION = "ADDTYPECATEGORYCOLLECTION";
export const PRICING = "PRICING";
export const VARIANT = "VARIANT";
export const REMOVEVARIANT = "REMOVEVARIANT";
export const ADDMOREVARIANT = "ADDMOREVARIANT";
export const VARIANTSUB = "VARIANTSUB";
export const ADDMORESUBVARIANT = "ADDMORESUBVARIANT";
export const SEOTAG = "SEOTAG";
export const REMOVESEOTAG = "REMOVESEOTAG";
export const ADDMORETAGS = "ADDMORETAGS";

// onBordingReducer

export const ADDONBOARDIMAGES = "ADDONBOARDIMAGES";
export const ADDONBOARDVIDEOS = "ADDONBOARDVIDEOS";
